---
image: docker:latest
services:
  - docker:dind

stages:
  - tests

before_script:
  - apk update && apk add --no-cache
    python3-dev py3-pip gcc git curl build-base 
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh 

  - docker info
  - python3 --version
  - python3 -m pip install ansible yamllint ansible-lint pytest testinfra molecule[docker]
  - ansible --version
  - molecule --version

molecule-nginx-role:
  stage: tests
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
  script:
    - cd nginx-role
    - molecule test
