---
- name: Converge
  hosts: all
  tasks: 
    - name: Update cache (RedHat)
      yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Update cache (Debian)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
