---
    # tasks file for nginx-role
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Enable and running nginx
      service:
        name: nginx
        enabled: yes
        state: started