# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Python 3.x
      uses: actions/setup-python@v2
      with: 
        python-version: 3.x
      
    # Runs a set of commands using the runners shell
    - name: Install all molecule dependencies
      run: pip3 install molecule[docker] yamllint ansible-lint testinfra pytest
      
    - name: Create init role
      run: molecule init role --verifier-name testinfra -d docker nginx-role
      
    - name: Molecule test
      run: |
        cd nginx-role
        molecule test
